apiVersion: v1
kind: Service
metadata:
  name: {{ include "dental-backend.fullname" . }}
  labels:
    {{- include "dental-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP      
      name: http
      nodePort: 30066
  selector:
    {{- include "dental-backend.selectorLabels" . | nindent 4 }}
