apiVersion: v1
kind: Service
metadata:
  name: {{ include "dental-frontend.fullname" . }}
  labels:
    {{- include "dental-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP      
      name: http
      nodePort: 30088
  selector:
    {{- include "dental-frontend.selectorLabels" . | nindent 4 }}
